name: Automatic Deployment to Remote
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:

  build:
    name: Copy files and Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "feed_me_mensa_ul.py, Dockerfile, requirements.txt"
        target: "feed-me-mensa-ul"
    
    - name: build docker image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script:  docker image build -t feed-me-mensa-ul:latest feed-me-mensa-ul/  && docker container run --env-file ${{ secrets.TEST_ENV }} feed-me-mensa-ul:latest

        